billofmaterials:
  table-name: billofmaterials
  schema: production
  query: SELECT
      *
    FROM
      billofmaterials
  incremental: true
  incremental-filter: modifieddate
  spec: production/billofmaterials
culture:
  table-name: culture
  schema: production
  query: SELECT
      *
    FROM
      culture
  incremental: true
  incremental-filter: modifieddate
  spec: production/culture